title: Alejandro Brillembourg Cuenca
logo: "https://github.com/ajbrillembourg/ajbrillembourg/blob/108c34ef9134f88cccaee06b56c14dbc8dc6d913/images/logo.png"
description: >
  <p>Contained herein is a portfolio of academic and career highlights to accompany my LinkedIn online resume</p>
  <br><br>
  <a href="https://www.linkedin.com/in/alejandrobrillembourg/" "target="_blank">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
