title: Alejandro Brillembourg Cuenca
logo: "images/Brillembourg_Alejandro_circ_600px.jpg"
description: >
  <p>Contained herein is a portfolio of academic and career highlights to accompany my LinkedIn online resume</p>
  <br><br>
  <a href="https://www.linkedin.com/in/alejandrobrillembourg/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
