title: Alejandro Brillembourg Cuenca
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Contained herein is a portfolio of career highlights to accompany my LinkedIn online resume 
  <br><br>
  <a href="https://www.linkedin.com/in/alejandrobrillembourg/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
